name: hedieaty
description: "Hedieaty Wish List"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  flutter_gradient_app_bar: ^0.3.1
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  shared_preferences: ^2.3.3
  http: ^1.2.2
  intl: ^0.20.1
  image_picker: ^1.1.2
  provider: ^6.1.2

  flutter:
    sdk: flutter

  integration_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.png